# Use root/example as user/password credentials
version: "3.1"

services:
  dmmongo:
    container_name: mongo
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: dmadminuser
      MONGO_INITDB_ROOT_PASSWORD: 3xtrat3rr3str3
    # network_mode: bridge
    ports:
      - 27017:27017
    volumes:
      - dmsocial
  dmmongo-express:
    container_name: dmmongo-express
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: dmadminuser
      ME_CONFIG_MONGODB_ADMINPASSWORD: 3xtrat3rr3str3
    # network_mode: bridge
volumes:
  dmsocial: ~
